- name: varibles from prompt
  hosts:  localhost
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username?
    private: false
  - name: password
    prompt: Please enter password
    private: true
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg:  "Hello, Username is: {{username}}"